/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-15 02:38:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entity.user;
import com.entity.BookDtls;
import java.util.List;
import com.DAO.BookDAOImpl;
import java.sql.Connection;
import com.DB.DBConnect;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/all_component/allCss.jsp", Long.valueOf(1757592224908L));
    _jspx_dependants.put("jar:file:/C:/Users/Shivam/Desktop/Ebook/BABA/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Ebook-App/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1754062823137L));
    _jspx_dependants.put("/all_component/nav.jsp", Long.valueOf(1757903322075L));
    _jspx_dependants.put("/all_component/footer.jsp", Long.valueOf(1757903373956L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.entity.user");
    _jspx_imports_classes.add("com.entity.BookDtls");
    _jspx_imports_classes.add("com.DAO.BookDAOImpl");
    _jspx_imports_classes.add("com.DB.DBConnect");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Ebook: Index</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"all_component/style.css\">");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".back-img {\r\n");
      out.write("    background: url(\"img/book.webp\") center/cover no-repeat;\r\n");
      out.write("    height: 50vh;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-img::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0; left: 0; right: 0; bottom: 0;\r\n");
      out.write("    background: rgba(0,0,0,0.5); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ebook-title {\r\n");
      out.write("    position: relative; \r\n");
      out.write("    font-size: 52px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color: #fff; /* white text */\r\n");
      out.write("    text-shadow: 0 0 10px #ff3c3c, 0 0 20px #ff3c3c, 0 0 40px #ff0000;\r\n");
      out.write("    animation: glow 2s infinite alternate;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes glow {\r\n");
      out.write("    from {\r\n");
      out.write("        text-shadow: 0 0 5px #ff3c3c, 0 0 10px #ff5e5e, 0 0 20px #ff7e7e;\r\n");
      out.write("    }\r\n");
      out.write("    to {\r\n");
      out.write("        text-shadow: 0 0 20px #ff0000, 0 0 30px #ff3333, 0 0 60px #ff6666;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write(".btn-premium {\r\n");
      out.write("    background-color: #2c2f33; /* Dark charcoal */\r\n");
      out.write("    color: #fff;               /* White text */\r\n");
      out.write("    border: 1px solid #2c2f33;\r\n");
      out.write("    transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-premium:hover {\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    color: #2c2f33;\r\n");
      out.write("    border: 1px solid #2c2f33;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".crd-ho:hover {\r\n");
      out.write("	background-color: #fcf7f7;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: #f7f7f7;\">\r\n");
      out.write("\r\n");
      out.write("	");

	user u = (user) session.getAttribute("userobj");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Top Thin Bar -->\r\n");
      out.write("<div class=\"container-fluid\" style=\"height: 10px; background-color: #111827;\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Logo + Search + User Section -->\r\n");
      out.write("<div class=\"container-fluid p-4 bg-dark text-white shadow-sm\">\r\n");
      out.write("  <div class=\"row align-items-center\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <div class=\"col-md-3 text-warning\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <i class=\"fa-solid fa-book\"></i> Ebooks\r\n");
      out.write("      </h3>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Search -->\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <form class=\"form-inline my-2 my-lg-0\" action=\"search.jsp\" method=\"post\">\r\n");
      out.write("        <input class=\"form-control mr-sm-2 w-75\" type=\"search\" name=\"ch\"\r\n");
      out.write("          placeholder=\"Search for books...\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-warning my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- User Section -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\" style=\"background-color: #111827;\">\r\n");
      out.write("  <a class=\"navbar-brand text-warning\" href=\"#\"><i class=\"fa-solid fa-house\"></i></a>\r\n");
      out.write("  <button class=\"navbar-toggler text-white\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("    data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" \r\n");
      out.write("    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("      <li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"all_recent_book.jsp\"><i class=\"fa-solid fa-book-open\"></i> Recent Books</a></li>\r\n");
      out.write("      <li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"all_new_book.jsp\"><i class=\"fa-solid fa-book-open\"></i> New Books</a></li>\r\n");
      out.write("      <li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"all_old_book.jsp\"><i class=\"fa-solid fa-book-open\"></i> Old Books</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("      <a href=\"setting.jsp\" class=\"btn btn-outline-warning my-2 my-sm-0\">\r\n");
      out.write("        <i class=\"fa-solid fa-gear\"></i> Setting\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"helpline.jsp\" class=\"btn btn-outline-warning my-2 my-sm-0 ml-2\">\r\n");
      out.write("        <i class=\"fa-solid fa-phone\"></i> Contact Us\r\n");
      out.write("      </a>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Hover Style -->\r\n");
      out.write("<style>\r\n");
      out.write("  .navbar a.nav-link:hover {\r\n");
      out.write("    color: #FBBF24 !important; /* Gold hover */\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-brand:hover {\r\n");
      out.write("    color: #FFD700 !important; /* Premium Gold */\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<!-- Hero Section -->\r\n");
      out.write("<div class=\"container-fluid\" style=\"background: linear-gradient(rgba(17,24,39,0.8), rgba(17,24,39,0.8)), url('img/book.webp') center/cover no-repeat; height: 50vh;\">\r\n");
      out.write("    <div class=\"d-flex flex-column justify-content-center align-items-center h-100 text-center text-white\">\r\n");
      out.write("        <h1 class=\"display-4 fw-bold\" style=\"color: #FFD700;\">Ebook Management System</h1>\r\n");
      out.write("        <p class=\"lead mt-2\" style=\"color: #ffffffaa;\">Discover, Read, and Buy Your Favorite Books</p>\r\n");
      out.write("        <a href=\"all_recent_book.jsp\" class=\"btn btn-warning btn-lg mt-3\">Browse Books</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- RECENT BOOK -->\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<h3 class=\"text-center\">Recent Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");

			BookDAOImpl dao2 = new BookDAOImpl(DBConnect.getConn());
			List<BookDtls> list2 = dao2.getRecentBook();
			for (BookDtls b : list2) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"Book/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumbnail\">\r\n");
      out.write("						<p>");
      out.print(b.getBookName());
      out.write("</p>\r\n");
      out.write("						<p>");
      out.print(b.getAuthor());
      out.write("</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories:\r\n");
      out.write("							");
      out.print(b.getBookCategory());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("						");

						if (b.getBookCategory().equals("Old")) {
						
      out.write("\r\n");
      out.write("						<div class=\"text-center mt-2\">\r\n");
      out.write("							<a href=\"view_books.jsp?bid=");
      out.print(b.getBookId());
      out.write("\" class=\"btn btn-success btn-sm mx-1\">View Details</a> <a\r\n");
      out.write("								href=\"\" class=\"btn btn-warning btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-indian-rupee-sign\"></i> ");
      out.print(b.getPrice());
      out.write("\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<div class=\"text-center mt-2\">\r\n");
      out.write("							");

							if (u == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"login.jsp\" class=\"btn btn-danger btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-cart-plus\"></i> Add Cart\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"cart?bid=");
      out.print(b.getBookId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-cart-plus\"></i> Add Cart\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<a href=\"view_books.jsp?bid=");
      out.print(b.getBookId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm mx-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-warning btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-indian-rupee-sign\"></i> ");
      out.print(b.getPrice());
      out.write("\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("			<a href=\"all_recent_book.jsp\" class=\"btn btn-premium btn-sm\">View All</a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- END OF RECENT BOOKS -->\r\n");
      out.write("\r\n");
      out.write("	<!-- NEW BOOK -->\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<h3 class=\"text-center\">New Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("			");

			BookDAOImpl dao = new BookDAOImpl(DBConnect.getConn());
			List<BookDtls> list = dao.getNewBook();
			for (BookDtls b : list) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"Book/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumbnail\">\r\n");
      out.write("						<p>");
      out.print(b.getBookName());
      out.write("</p>\r\n");
      out.write("						<p>");
      out.print(b.getAuthor());
      out.write("</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories:\r\n");
      out.write("							");
      out.print(b.getBookCategory());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"text-center mt-2\">\r\n");
      out.write("							");

							if (u == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"login.jsp\" class=\"btn btn-danger btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-cart-plus\"></i> Add Cart\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"cart?bid=");
      out.print(b.getBookId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-cart-plus\"></i> Add Cart\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<a href=\"view_books.jsp?bid=");
      out.print(b.getBookId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm mx-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-warning btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-indian-rupee-sign\"></i> ");
      out.print(b.getPrice());
      out.write("\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("			<a href=\"all_recent_book.jsp\" class=\"btn btn-premium btn-sm\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- END OF NEW BOOKS -->\r\n");
      out.write("	<!-- OLD BOOK -->\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<h3 class=\"text-center\">Old Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");

			BookDAOImpl dao3 = new BookDAOImpl(DBConnect.getConn());
			List<BookDtls> list3 = dao3.getOldBooks();

			for (BookDtls b : list3) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"Book/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\" class=\"img-thumbnail\">\r\n");
      out.write("						<p>");
      out.print(b.getBookName());
      out.write("</p>\r\n");
      out.write("						<p>");
      out.print(b.getAuthor());
      out.write("</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories:\r\n");
      out.write("							");
      out.print(b.getBookCategory());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"text-center mt-2\">\r\n");
      out.write("							<a href=\"view_books.jsp?bid=");
      out.print(b.getBookId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm mx-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-warning btn-sm mx-1\"> <i\r\n");
      out.write("								class=\"fa-solid fa-indian-rupee-sign\"></i>");
      out.print(b.getPrice());
      out.write("\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("			<a href=\"all_recent_book.jsp\" class=\"btn btn-premium btn-sm\">View All</a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("	<!-- END OF OLD BOOKS -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<footer class=\"text-white mt-4\" style=\"background-color: #111827;\">\r\n");
      out.write("  <div class=\"container p-4\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- About Section -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <h5 class=\"text-warning\">E-Book Management System</h5>\r\n");
      out.write("        <p>\r\n");
      out.write("          A platform to explore, buy, and manage e-books. \r\n");
      out.write("          Find the latest, new, and old books in one place.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Quick Links -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <h5 class=\"text-warning\">Quick Links</h5>\r\n");
      out.write("        <ul class=\"list-unstyled\">\r\n");
      out.write("          <li><a href=\"index.jsp\" class=\"text-white text-decoration-none\">Home</a></li>\r\n");
      out.write("          <li><a href=\"all_recent_book.jsp\" class=\"text-white text-decoration-none\">Recent Books</a></li>\r\n");
      out.write("          <li><a href=\"all_new_book.jsp\" class=\"text-white text-decoration-none\">New Books</a></li>\r\n");
      out.write("          <li><a href=\"all_old_book.jsp\" class=\"text-white text-decoration-none\">Old Books</a></li>\r\n");
      out.write("          <li><a href=\"helpline.jsp\" class=\"text-white text-decoration-none\">Contact Us</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Contact & Social -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <h5 class=\"text-warning\">Contact Us</h5>\r\n");
      out.write("        <p><i class=\"fa-solid fa-envelope text-warning\"></i> support@ebookapp.com</p>\r\n");
      out.write("        <p><i class=\"fa-solid fa-phone text-warning\"></i> +91 8591636011</p>\r\n");
      out.write("        <p><i class=\"fa-solid fa-location-dot text-warning\"></i> Mumbai, India</p>\r\n");
      out.write("\r\n");
      out.write("        <!-- Social Media Icons -->\r\n");
      out.write("        <a href=\"#\" class=\"text-white me-3\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("        <a href=\"#\" class=\"text-white me-3\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("        <a href=\"#\" class=\"text-white me-3\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bottom Bar -->\r\n");
      out.write("  <div class=\"text-center p-2\" style=\"background-color: #0f172a;\">\r\n");
      out.write("    <small>\r\n");
      out.write("      <i class=\"fa-solid fa-copyright text-warning\"></i> \r\n");
      out.write("      ");
      out.print( java.time.Year.now() );
      out.write(" | Design & Developed by <b class=\"text-warning\">Shivam Giri</b>\r\n");
      out.write("    </small>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  footer a:hover {\r\n");
      out.write("    color: #FBBF24 !important; /* Gold hover */\r\n");
      out.write("  }\r\n");
      out.write("  footer i.fa-brands:hover {\r\n");
      out.write("    color: #FFD700 !important; /* Bright premium gold */\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /all_component/nav.jsp(28,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      <div class=\"col-md-3 text-right\">\r\n");
        out.write("        <a href=\"checkout.jsp\" class=\"btn btn-outline-warning mr-2\"> \r\n");
        out.write("          <i class=\"fa-solid fa-cart-plus\"></i>\r\n");
        out.write("        </a> \r\n");
        out.write("        <a href=\"#\" class=\"btn btn-warning text-dark mr-2\">\r\n");
        out.write("          <i class=\"fa-solid fa-user\"></i> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userobj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("        </a> \r\n");
        out.write("        <a href=\"logout\" class=\"btn btn-danger text-white\">\r\n");
        out.write("          <i class=\"fa-solid fa-right-to-bracket\"></i> Logout\r\n");
        out.write("        </a>\r\n");
        out.write("      </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /all_component/nav.jsp(42,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      <div class=\"col-md-3 text-right\">\r\n");
        out.write("        <a href=\"login.jsp\" class=\"btn btn-warning text-dark mr-2\">\r\n");
        out.write("          <i class=\"fa-solid fa-right-to-bracket\"></i> Login\r\n");
        out.write("        </a> \r\n");
        out.write("        <a href=\"register.jsp\" class=\"btn btn-outline-warning\">\r\n");
        out.write("          <i class=\"fa-solid fa-user-plus\"></i> Register\r\n");
        out.write("        </a>\r\n");
        out.write("      </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
